[setup]
t_final = 10

[params]
size_x = 100
size_y = 100
delta = 15
dt = 0.1 #
c = 3.0 # Don't touch this.
dens = 2 # of prtls per species per cell
gamma_inj = 15.0 # Speed of upstream flow
n_pass = 4 # Number of filter passes.
